"use client";
import "./globals.css";
import { Inter } from "next/font/google";

import Footer from "../components/footer/Footer";
import Navbar from "../components/navbar/Navbar";
import SessionProvider from "./SessionProvider";
import { SessionCtx } from "./SessionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <SessionCtx>
            <Navbar />
            {children}
            <Footer />
          </SessionCtx>
        </SessionProvider>
      </body>
    </html>
  );
}
